var string1 = "Cats";
console.log("what is the best animal? ", string1);
var string2 = "Kangaroos";
console.log("what is the second best animal? ", string2);
var string3 = "Owls";
console.log("What is the wisest animal...", string3);
var num1 = 0;
console.log("how many dollars do I have? ", num1);
var num2 = 3.14159;
console.log("I love pi! ", num2);
var num3 = -42;
console.log("Not quite the answer to the universe, ", num3);
var num4 = -1;
console.log("not a good boolean value, ", num4);
boolean cool = true;
console.log("first boolean: ", cool);
boolean cold = false;
console.log("second boolean: ", cold);
var unknown;
console.log("Not sure what this will print: ", unknown);